### ISSUE TITLE
Tシャツの販売額がおかしい

### ISSUE THREAD

**Issue by tomoyuki1110** [DecodeLLC/couple-t-android#265]
Tシャツの販売額が、アイテム価格は入っているが
表裏袖に、デザインを入れているにも関わらずその価格が反映していない。
![screenshot_20170525-233306](https://cloud.githubusercontent.com/assets/17405609/26454819/24c7c56c-41a3-11e7-9214-02ebe1ce7714.png)

**Comment by alexeypolitov** [comment]
@tomoyuki1110 @take-iwa 修正しました。新しいバージョンでご確認ください。
