### ISSUE TITLE
プロフィールで性別を設定しても検索で引っかからない

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/couple-t-android#270]
アンドロイド版でプロフィールの性別を設定しても
他のユーザーから性別フィルターで検索した時、結果に出てこない。

年齢やユーザー位置は検索結果に反映されている。

**Comment by take-iwa** [comment]
@alexeypolitov ver1.0(66)で確認しましたが、性別「女性」で検索した時に女性で登録した他のテストユーザーが出てきません。確認お願いいたします。

**Comment by alexeypolitov** [comment]
@take-iwa ログインしたユーザーIPASSと出てこないユーザーの名前を教えて下さい

**Comment by take-iwa** [comment]
@alexeypolitov 
ログインユーザー
h.ooiwa@maruig.co.jp/maruiorimono
出てこないユーザー名
oriori
一応、ipassも
h.ooiwa@maruiorimono.jp/test

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。
